### ISSUE TITLE
Adicionar nome como colaborador na descrição.

### ISSUE THREAD

**Issue by PilzTol** [PilzTol/GCMS-Wallisson-Rocha#1]
@ramidedantas 
[README](https://github.com/PilzTol/GCMS-Wallisson-Rocha/blob/main/README.md)

**Comment by ramidedantas** [comment]
@PilzTol faltou me marcar

**Comment by PilzTol** [comment]
Corrigido. Vou fechar a issue

**Comment by PilzTol** [comment]
Achei que o convite já havia sido enviado. Devo ter cometido algum engano ou erro. Enviei o convite.

**Comment by ramidedantas** [comment]
@PilzTol feito.
